
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
#
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

development:
    pool: 5
    adapter: postgresql
    database: prueba-045